hermes:
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    consumer:
      group-id: hmtl-handler
      topic: html-extraction
    producer:
      topic: analyzer-service
      key: html-handler
  cache:
    valid-interval: 60000
    redis:
      host: localhost
      port: 6379
