/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hermes.app;

import org.hermes.list.LinkedList;

import static org.hermes.utilities.StringUtils.join;
import static org.hermes.utilities.StringUtils.split;
import static org.hermes.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {

    public static void main(String[] args) {
    }
}
